services:
    invokable_controller:
        class: App\Controller\InvokableController
        autoconfigure: true # Not works
#        autowire: true # Works
#        tags: ['container.service_subscriber', 'controller.service_arguments' ] # Not works
#        tags: ['controller.service_arguments'] # Not works
#        tags: ['container.service_subscriber'] # Not works
